#Add Routing
spring.cloud.gateway.server.webflux.routes[0].id=PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCTSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/product/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=ProductService
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/productFallback

spring.cloud.gateway.server.webflux.routes[1].id=ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order/**

management.endpoints.web.exposure.include=*
 
 
#Circuit Breaker
resilience4j.circuitbreaker.instances.ProductService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ProductService.slidingWindowSize=6
resilience4j.circuitbreaker.instances.ProductService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ProductService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.ProductService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.ProductService.minimumNumberOfCalls=5
